// expenses
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const START_ADD_EXPENSE = 'START_ADD_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const START_EDIT_EXPENSE = 'START_EDIT_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const START_REMOVE_EXPENSE = 'START_REMOVE_EXPENSE';
export const SET_EXPENSE = 'SET_EXPENSE';
export const START_SET_EXPENSE = 'START_SET_EXPENSE';

// filters
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';

// auth
export const LOGIN = 'LOGIN';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET';
export const SEND_PASSWORD_RESET_ERROR = 'SEND_PASSWORD_RESET_ERROR';