// expenses
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const START_ADD_EXPENSE = 'START_ADD_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const START_EDIT_EXPENSE = 'START_EDIT_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const START_REMOVE_EXPENSE = 'START_REMOVE_EXPENSE';
export const SET_EXPENSE = 'SET_EXPENSE';
export const START_SET_EXPENSE = 'START_SET_EXPENSE';

// filters
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';

// auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// setter auth
export const SET_SEND_PASSWORD_RESET_ERROR = 'SET_SEND_PASSWORD_RESET_ERROR';
export const SET_SEND_PASSWORD_RESET_SUCCESS = 'SET_SEND_PASSWORD_RESET_SUCCESS';
export const SET_CREATE_USER_ERROR = 'SET_CREATE_USER_ERROR';
export const SET_AUTH_USER_PROFILE = 'SET_AUTH_USER_PROFILE';
export const SET_AUTH_LOGIN_ERROR = 'SET_AUTH_LOGIN_ERROR';
export const SET_LINK_EMAIL_AUTH_PROVIDER_ERROR = 'SET_LINK_EMAIL_AUTH_PROVIDER_ERROR';
export const SET_LINK_EMAIL_AUTH_PROVIDER_SUCCESS = 'SET_LINK_EMAIL_AUTH_PROVIDER_SUCCESS';
export const SET_CURRENT_SIGN_IN_METHOD = 'SET_CURRENT_SIGN_IN_METHOD';
export const SET_CLOSE_LINK_EMAIL_MODAL = 'SET_CLOSE_LINK_EMAIL_MODAL';
export const SET_SIGN_IN_PROVIDER = 'SET_SIGN_IN_PROVIDER';

// async auth
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const START_CREATE_USER = 'START_CREATE_USER';
export const START_SEND_PASSWORD_RESET = 'START_SEND_PASSWORD_RESET';
export const START_LINK_EMAIL_AUTH_PROVIDER = 'START_LINK_EMAIL_AUTH_PROVIDER';
export const START_LINK_AUTH_PROVIDER = 'START_LINK_AUTH_PROVIDER';
export const START_UNLINK_AUTH_PROVIDER = 'START_UNLINK_AUTH_PROVIDER';
